server:
  port: 8081
  servlet:
    context-path: /bridge

spring:
  application:
    name: onms-cloud-bridge
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    default-property-inclusion: non_null
  
# Security configuration
security:
  user:
    name: admin
    # This is a default password for development
    # In production, this should be externalized and secured
    password: admin123
    roles: ADMIN

# Management endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Logging configuration
logging:
  level:
    root: INFO
    org.opennms.bridge: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

# Application specific configuration
bridge:
  discovery:
    # Maximum number of concurrent discovery jobs
    max-concurrent-jobs: 5
    # Default timeout for discovery jobs in seconds
    default-timeout: 300
  collection:
    # Default interval for scheduled collections in minutes
    default-interval: 15
    # Maximum number of concurrent collection jobs
    max-concurrent-jobs: 10